### ISSUE TITLE
Feature: Quotes can be favorited 

### ISSUE THREAD

**Issue by michaelsoliman1** [mudroljub/programming-quotes-api#49]
Hi, It's Michael again xD, I just saw the endpoints for registering and authentication, It's so great you did that as I'm looking for a solution to add authentication to my app, and this is perfect!.

So the feature is to add the ability for each user to add quotes to favorites, and also get a list of his favorited quotes.

Thank You for This!

**Comment by mudroljub** [comment]
I tried to add this feature, but for some reason it doesn't work.

I created a new endpoint for adding a favorite quote, which seems to work, but after that it doesn't return a list of favorite quotes for the logged in user.

It would be helpful to have someone besides me look at the code.

**Comment by Anirud2002** [comment]
I have pulled a PR up that resolves this issue.

![image](https://github.com/mudroljub/programming-quotes-api/assets/71384179/b16b004d-c974-4152-bd13-220c0c97b7ea)
