### ISSUE TITLE
API going away because Heroku no longer has a free plan

### ISSUE THREAD

**Issue by quinncomendant** [mudroljub/programming-quotes-api#54]
Heroku will [no longer have free hosting](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq). Does this mean the `programming-quotes-api.herokuapp.com` API will be going away? Or will you find an alternate home for it?

**Comment by quinncomendant** [comment]
Alternatives include [GCP Cloud Run](https://cloud.google.com/run), [Render](https://render.com/), [Fly](https://fly.io/), or [Railway](https://railway.app/). :)

**Comment by SwiftyProgrammer690** [comment]
Replit too!

**Comment by quinncomendant** [comment]
Y’all – if you just want to get all quotes or one random quote (and don't mind a 34KB response), *you can still use the “alternative API”:*

# Get all quotes:

```bash
curl -s --compressed https://raw.githubusercontent.com/skolakoda/programming-quotes-api/master/Data/quotes.json
```

# Get a random quote:

```bash
curl -s --compressed https://raw.githubusercontent.com/skolakoda/programming-quotes-api/master/Data/quotes.json | jq ".[$((RANDOM%501))]"
```

😜

**Comment by thinhnguyeniosdev** [comment]
Thanks for the fix!

**Comment by mudroljub** [comment]
I've had a look at some of the proposed alternatives, but I don't have that much time to try and compare each one. It would be very useful if someone wants to help deploy the project to one of the free platforms.

**Comment by ahujaesh** [comment]
you can also use github pages  - I use it for my DI team's website and it works well for me - https://ahujaesh.github.io

**Comment by quinncomendant** [comment]
Hi @ahujaesh,

> you can also use github pages

We love GitHub pages, [but it only hosts static content](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#about-github-pages). This API requires hosting code that runs on the server (unless you're referring to just loading the JSON file as per [my hack above](https://github.com/mudroljub/programming-quotes-api/issues/54#issuecomment-1439289920), in which case the content is already hosted by github 🙃).

**Comment by ahujaesh** [comment]
Oh my bad - I'm new to GitHub pages and I use it for HTML, which is static
