### ISSUE TITLE
remove Helpers, move settings to env

### ISSUE THREAD

**Issue by X7REME13** [mudroljub/programming-quotes-api#66]
Hi! I see that you have TODOs in your readme. I'm a .NET developer; maybe I can help you with `remove Helpers, move settings to env`. Tell me if you want me to do it.

**Comment by mudroljub** [comment]
Hi! If you think that it is a good practice, then you are very welcome to contribute.

**Comment by mudroljub** [comment]
https://github.com/mudroljub/programming-quotes-api/pull/69
