### ISSUE TITLE
Quoter.be : an app inspired by Your Project!

### ISSUE THREAD

**Issue by rdhainaut** [mudroljub/programming-quotes-api#67]
Hi,

I recently came across this project on GitHub, and it sparked some ideas that led to a project I've been working on. I m loving crafting some fun app, and your project gave me a great starting point.

I wanted to share the result with you: Quoter (https://quoter.be/), a free app designed to discover and share quotes. It's a small project, but I'm happy with the results. I thought it would be cool to share what others can build from your project. It s available [online at quoter.be ](https://quoter.be), it s available as PWA too  and available on [Microsoft Store](https://www.microsoft.com/store/productId/9P7TH1ML012D?ocid=pdpshare) 

Thank you for sharing your project with the community—it’s been really helpful for developers like myself!

Note: If you have a hosted version of your API, I could upgrade my project to request your API directly and include the newest quotes

**Comment by mudroljub** [comment]
You are welcome!
